#!/usr/bin/env python3
"""
Convert a TrueType font into a gfx.c bitmap font (assets/font_<name>.xbm).

gfx.c fonts are a single horizontal strip holding every glyph side by side,
plus a table of the x offset where each glyph starts (see DEFINE_FONT in
src/gfx.h). The strip is stored transposed so the blitter can copy whole
columns: each XBM row is one strip column, bit (y & 7) of byte y/8 is pixel y,
and a 0 bit is a lit pixel. This tool renders the glyphs without
anti-aliasing, crops them to a common vertical ink band, optionally scales
them, and writes that layout directly (no GIMP / `mogrify -flip -rotate 90`
round-trip).

The generated file starts with a comment holding the regeneration command and
the matching DEFINE_FONT(...) line to paste into the C source.

Usage:
    python3 tools/ttf2font.py FONT.ttf --name speed --chars ".0123456789" \\
        --size 17 --height 34 -o assets/font_speed.xbm --preview

Pixel fonts render cleanly only at their design size (or an integer multiple
of it): pick --size so that one design grid step lands on exactly one pixel,
then scale up with --scale-x / --scale-y / --height.

Requires Pillow (in the dev shell: nix-shell / nix develop).
"""

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont


def render_glyph(font, ch):
    """Render one character at 1 bpp. Returns (image, advance) where the image
    spans the glyph's advance horizontally and the full line box vertically."""
    ascent, descent = font.getmetrics()
    advance = int(round(font.getlength(ch)))
    left = min(0, font.getbbox(ch)[0])  # glyphs whose ink starts left of origin
    right = max(advance, font.getbbox(ch)[2])
    img = Image.new("1", (right - left, ascent + descent), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"  # no anti-aliasing
    draw.text((-left, 0), ch, font=font, fill=1)
    return img, advance, left


def column_range(img):
    """First/last+1 column containing ink, or None for a blank glyph."""
    bbox = img.getbbox()
    return (bbox[0], bbox[2]) if bbox else None


def stretch_rows(img, height):
    """Nearest-neighbour vertical resize to an exact pixel height."""
    return img.resize((img.width, height), Image.NEAREST)


def build_strip(args):
    font = ImageFont.truetype(args.font, args.size)
    chars = "".join(sorted(set(args.chars)))  # font_getchar() binary-searches
    if chars != args.chars:
        print(f"note: chars sorted/deduplicated to {chars!r}", file=sys.stderr)

    glyphs = [render_glyph(font, ch) for ch in chars]

    # Common vertical ink band so every glyph shares a baseline.
    tops, bots = [], []
    for img, _, _ in glyphs:
        bbox = img.getbbox()
        if bbox:
            tops.append(bbox[1])
            bots.append(bbox[3])
    if not tops:
        sys.exit("error: none of the requested characters has any ink")
    y0, y1 = min(tops), max(bots)

    cells = []
    for ch, (img, advance, left) in zip(chars, glyphs):
        if args.spacing is None:
            # Keep the font's own advance (built-in side bearings).
            cell = img.crop((-left, y0, -left + advance, y1))
        else:
            cols = column_range(img)
            if cols is None:  # blank glyph (space): keep its advance
                cell = img.crop((-left, y0, -left + advance, y1))
            else:
                ink = img.crop((cols[0], y0, cols[1], y1))
                cell = Image.new("1", (ink.width + args.spacing, ink.height), 0)
                cell.paste(ink, (0, 0))
        if args.scale_x != 1 or args.scale_y != 1:
            cell = cell.resize((cell.width * args.scale_x, cell.height * args.scale_y),
                               Image.NEAREST)
        if args.height:
            cell = stretch_rows(cell, args.height)
        cells.append(cell)

    height = cells[0].height
    offsets, x = [], 0
    for cell in cells:
        offsets.append(x)
        x += cell.width
    strip = Image.new("1", (x, height), 0)
    for off, cell in zip(offsets, cells):
        strip.paste(cell, (off, 0))
    return chars, strip, offsets


def xbm_bytes(strip):
    """Transposed, inverted XBM payload: one row per strip column."""
    w, h = strip.size
    px = strip.load()
    bpr = (h + 7) // 8
    out = []
    for x in range(w):
        row = [0xFF] * bpr  # 1 = unlit
        for y in range(h):
            if px[x, y]:
                row[y // 8] &= ~(1 << (y & 7))
        out.extend(row)
    return out


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_xbm(path, name, chars, strip, offsets, command):
    w, h = strip.size
    data = xbm_bytes(strip)
    define = f"DEFINE_FONT({name}, {c_string(chars)}, {', '.join(map(str, offsets[1:]))});"
    lines = [
        f"/* Generated by tools/ttf2font.py — do not edit by hand.",
        f" *   {command}",
        f" * Glyphs are {h} px tall; strip is {w} px wide.",
        f" * {define}",
        f" */",
        f"#define font_{name}_width {h}",
        f"#define font_{name}_height {w}",
        f"static char font_{name}_bits[] = {{",
    ]
    for i in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return define


def preview(strip, offsets):
    px = strip.load()
    starts = set(offsets)
    print("".join("|" if x in starts else " " for x in range(strip.width)))
    for y in range(strip.height):
        print("".join("#" if px[x, y] else "." for x in range(strip.width)))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("font", help="path to a .ttf/.otf file")
    ap.add_argument("--name", required=True, help="font name: font_<name>, img_font_<name>")
    ap.add_argument("--chars", required=True, help="characters to include")
    ap.add_argument("--size", type=int, required=True, help="render size in px (em size)")
    ap.add_argument("--scale-x", type=int, default=1, help="integer horizontal scale")
    ap.add_argument("--scale-y", type=int, default=1, help="integer vertical scale")
    ap.add_argument("--height", type=int,
                    help="stretch glyphs vertically to exactly this many px "
                         "(nearest neighbour; applied after --scale-*)")
    ap.add_argument("--spacing", type=int,
                    help="crop each glyph to its ink and add this many blank columns "
                         "after it, instead of using the font's advance widths")
    ap.add_argument("-o", "--output", help="output .xbm (default assets/font_<name>.xbm)")
    ap.add_argument("--preview", action="store_true", help="print the strip as ASCII art")
    args = ap.parse_args()

    chars, strip, offsets = build_strip(args)
    out = args.output or os.path.join("assets", f"font_{args.name}.xbm")
    # Record the invocation with a repo-independent font path.
    argv = [os.path.basename(args.font) if a == args.font else a for a in sys.argv[1:]]
    command = "tools/ttf2font.py " + " ".join(
        a if a and all(c.isalnum() or c in "-_./=" for c in a) else "'" + a + "'" for a in argv)
    define = write_xbm(out, args.name, chars, strip, offsets, command)

    if args.preview:
        preview(strip, offsets)
    print(f"wrote {out}: {len(chars)} glyphs, {strip.width}x{strip.height} px", file=sys.stderr)
    print(define)


if __name__ == "__main__":
    main()
